### ISSUE TITLE
Forking Workflow

### ISSUE THREAD

**Issue by ioana229** [MarvinBS-Erlangen/Coffee_on_the_laptop#2]

**Comment by MarvinBS-Erlangen** [comment]
1. bei der Arbeit mit Open-Source-Projekten verwendet
2. Dieser Workflow basiert auf der Idee, dass Entwickler oder Mitwirkende ihre eigene Kopie (Fork) eines Repositorys erstellen und dann Änderungen in dieser eigenen Kopie vornehmen
3. Sobald die Änderungen abgeschlossen sind, werden sie über eine "Pull Request" oder "Merge Request" zur Hauptquelle des Projekts vorgeschlagen.
4. Der Hauptentwickler oder das Team kann dann entscheiden, ob die Änderungen übernommen werden.
