### ISSUE TITLE
Pull-Request Workflow

### ISSUE THREAD

**Issue by ioana229** [MarvinBS-Erlangen/Coffee_on_the_laptop#4]

**Comment by MarvinBS-Erlangen** [comment]
1. Der Pull-Request-Workflow (PR-Workflow) ist ein beliebter Arbeitsablauf in der Softwareentwicklung, insbesondere bei der Arbeit mit Versionskontrollsystemen wie Git und Plattformen wie GitHub, GitLab oder Bitbucket.
2. Bei diesem Workflow arbeiten Entwickler an einer gemeinsamen Codebasis, indem sie Änderungen in einem Branch (einem Zweig) des Repositories vornehmen und diese Änderungen über einen Pull Request (PR) zur Integration in das Haupt-Repository (meistens den main- oder master-Branch) vorschlagen.

**Comment by ioana229** [comment]
**Pull Request Workflow:** Ein Prozess, bei dem Entwickler Änderungen in einem separaten Branch vornehmen und diese über einen Pull Request zur Überprüfung und Integration in den Hauptbranch vorschlagen. Fokus liegt auf Code-Review und Kollaboration.

**GitHub Workflow:** Eine breitere Definition, die standardisierte Prozesse für die Zusammenarbeit in Repositories umfasst. Dazu gehören Branching-Strategien, Automatisierungen (z. B. GitHub Actions), und allgemeine Praktiken für Versionskontrolle.
Kurz: Pull Request Workflow ist ein Teil eines umfassenderen GitHub Workflows.
